services:
  - type: web
    name: todo-backend
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./02_Backend_SpringBoot/Dockerfile
    dockerContext: ./02_Backend_SpringBoot
    healthCheckPath: /api/todos/health
    envVars:
      - key: SERVER_PORT
        value: 10000
      - key: SPRING_PROFILES_ACTIVE
        value: prod
